export interface Workspace {
	id: string;
	label: string;
	category: string;
	description: string;
	path: string;
	type: "rust" | "npm";
}

export const workspaces: Workspace[] = [
	{
		id: "root-package-json",
		label: "@wrikka/rust-packages",
		category: "Root",
		description: "",
		path: "package.json",
		type: "npm",
	},
	{
		id: "root-cargo",
		label: "rust-packages",
		category: "Root",
		description: "Cargo workspace root for rust-packages",
		path: "Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-cli-agent-browser-Cargo-rust",
		label: "agent-browser",
		category: "CLI Apps",
		description:
			"Browser automation agent with Clean Architecture - supports Chrome, Firefox, Safari, Edge",
		path: "apps/cli/agent-browser/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-cli-agent-capture-Cargo-rust",
		label: "agent-capture",
		category: "CLI Apps",
		description:
			"Multi-platform agent capture CLI for browser, terminal, code snippets, and component previews",
		path: "apps/cli/agent-capture/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-cli-agent-capture-package-npm",
		label: "@wrikka/agent-capture",
		category: "CLI Apps",
		description:
			"Multi-platform agent capture CLI for browser, terminal, code snippets, and component previews",
		path: "apps/cli/agent-capture/package.json",
		type: "npm",
	},
	{
		id: "apps-cli-agent-computer-Cargo-rust",
		label: "agent-computer",
		category: "CLI Apps",
		description:
			"Main orchestration for computer automation with Clean Architecture",
		path: "apps/cli/agent-computer/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-cli-agent-computer-package-npm",
		label: "@wrikka/rust-agent-computer",
		category: "CLI Apps",
		description: "Computer automation agent with Clean Architecture",
		path: "apps/cli/agent-computer/package.json",
		type: "npm",
	},
	{
		id: "apps-cli-convert-web-to-desktop-Cargo-rust",
		label: "wrikka-convert-web-to-desktop",
		category: "CLI Apps",
		description:
			"CLI tool to convert web applications to desktop using Tauri + WebView",
		path: "apps/cli/convert-web-to-desktop/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-cli-convert-web-to-desktop-package-npm",
		label: "@wrikka/rust-convert-web-to-desktop",
		category: "CLI Apps",
		description: "Convert web apps to desktop with Clean Architecture",
		path: "apps/cli/convert-web-to-desktop/package.json",
		type: "npm",
	},
	{
		id: "apps-cli-monorepo-Cargo-rust",
		label: "wmonorepo",
		category: "CLI Apps",
		description:
			"Advanced monorepo management tool - Better than Moonrepo and Turborepo",
		path: "apps/cli/monorepo/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-cli-monorepo-package-npm",
		label: "@wrikka/rust-wmonorepo",
		category: "CLI Apps",
		description: "Monorepo management tool with Clean Architecture",
		path: "apps/cli/monorepo/package.json",
		type: "npm",
	},
	{
		id: "apps-desktop-files-desktop-package-npm",
		label: "@wrikka/files-desktop",
		category: "Desktop Apps",
		description:
			"Wrikka Desktop Explorer — custom-column, agent-driven file explorer",
		path: "apps/desktop/files-desktop/package.json",
		type: "npm",
	},
	{
		id: "apps-desktop-files-desktop-src-tauri-Cargo-rust",
		label: "wrikka-files-desktop",
		category: "Desktop Apps",
		description:
			"Wrikka Desktop Explorer — custom-column, agent-driven file explorer",
		path: "apps/desktop/files-desktop/src-tauri/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-desktop-terminal-desktop-package-npm",
		label: "@wrikka/terminal",
		category: "Desktop Apps",
		description: "Wrikka Terminal - GPU-accelerated terminal emulator",
		path: "apps/desktop/terminal-desktop/package.json",
		type: "npm",
	},
	{
		id: "apps-desktop-terminal-desktop-src-tauri-Cargo-rust",
		label: "wrikka-terminal",
		category: "Desktop Apps",
		description:
			"Wrikka Terminal - GUI Terminal Emulator with GPU-accelerated Rendering",
		path: "apps/desktop/terminal-desktop/src-tauri/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-tui-agent-tui-Cargo-rust",
		label: "agent-tui",
		category: "TUI Apps",
		description:
			"Terminal-based AI assistant interface with clean architecture",
		path: "apps/tui/agent-tui/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-tui-api-tui-Cargo-rust",
		label: "api-tui",
		category: "TUI Apps",
		description: "API client TUI app with clean architecture",
		path: "apps/tui/api-tui/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-tui-database-tui-Cargo-rust",
		label: "database-tui",
		category: "TUI Apps",
		description: "Database explorer TUI app with clean architecture",
		path: "apps/tui/database-tui/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-tui-editor-tui-Cargo-rust",
		label: "wrikka-editor-tui",
		category: "TUI Apps",
		description: "Modal TUI text editor with clean architecture",
		path: "apps/tui/editor-tui/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-tui-files-tui-Cargo-rust",
		label: "files-tui",
		category: "TUI Apps",
		description: "File explorer TUI app with clean architecture",
		path: "apps/tui/files-tui/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-tui-git-tui-Cargo-rust",
		label: "git-tui",
		category: "TUI Apps",
		description: "Git manager TUI app with clean architecture",
		path: "apps/tui/git-tui/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-tui-system-tui-Cargo-rust",
		label: "system-tui",
		category: "TUI Apps",
		description: "System monitor TUI app with clean architecture",
		path: "apps/tui/system-tui/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-tui-task-tui-Cargo-rust",
		label: "task-tui",
		category: "TUI Apps",
		description: "Tasks manager TUI app with clean architecture",
		path: "apps/tui/task-tui/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-tui-terminal-tui-Cargo-rust",
		label: "terminal-tui",
		category: "TUI Apps",
		description: "Terminal emulator TUI app with clean architecture",
		path: "apps/tui/terminal-tui/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-wasm-canvas-native-rust-Cargo-rust",
		label: "wcanvas-native-rust",
		category: "WASM Apps",
		description:
			"Native Rust implementation for wcanvas with storage, AI, and canvas core features",
		path: "apps/wasm/canvas/native-rust/Cargo.toml",
		type: "rust",
	},
	{
		id: "apps-wasm-canvas-package-npm",
		label: "@wrikka/wwhiteboard",
		category: "WASM Apps",
		description: "Whiteboard application with Rust WASM and SolidJS",
		path: "apps/wasm/canvas/package.json",
		type: "npm",
	},
	{
		id: "apps-wasm-canvas-web-package-npm",
		label: "@wrikka/wwhiteboard-web",
		category: "WASM Apps",
		description:
			"@wrikka/wwhiteboard-web npm workspace at apps/wasm/canvas/web/package.json",
		path: "apps/wasm/canvas/web/package.json",
		type: "npm",
	},
	{
		id: "apps-web-wpackages-package-npm",
		label: "wpackages",
		category: "Web Apps",
		description: "wpackages npm workspace at apps/web/wpackages/package.json",
		path: "apps/web/wpackages/package.json",
		type: "npm",
	},
	{
		id: "packages-domain-agent-sdk-channels-Cargo-rust",
		label: "agent-sdk-channels",
		category: "Domain",
		description:
			"Communication channels for agent-sdk: Slack, WhatsApp, Email, reconnection",
		path: "packages/domain/agent-sdk/channels/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-domain-agent-sdk-core-Cargo-rust",
		label: "wrikka-agent-core",
		category: "Domain",
		description:
			"AI agent core runtime - conversation, provider, memory, workspace",
		path: "packages/domain/agent-sdk/core/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-domain-agent-sdk-integrations-Cargo-rust",
		label: "agent-sdk-integrations",
		category: "Domain",
		description:
			"Integrations for agent-sdk: MCP OAuth, computer-use, web search/fetch",
		path: "packages/domain/agent-sdk/integrations/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-domain-agent-sdk-security-Cargo-rust",
		label: "agent-sdk-security",
		category: "Domain",
		description:
			"Security module for agent-sdk: audit log, crypto, RBAC, rate limiting",
		path: "packages/domain/agent-sdk/security/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-domain-agent-sdk-tools-Cargo-rust",
		label: "wrikka-agent-tools",
		category: "Domain",
		description: "Agent tools - shell, browser, review, git",
		path: "packages/domain/agent-sdk/tools/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-domain-terminal-sdk-Cargo-rust",
		label: "wrikka-terminal-sdk",
		category: "Domain",
		description:
			"Shared terminal SDK - core domain logic, ports, and adapters for terminal applications",
		path: "packages/domain/terminal-sdk/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-infra-caching-Cargo-rust",
		label: "wrikka-caching",
		category: "Infra",
		description:
			"High-performance concurrent caching with KV cache compression",
		path: "packages/infra/caching/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-infra-core-Cargo-rust",
		label: "wrikka-core",
		category: "Infra",
		description:
			"Core infrastructure - shared kernel, HTTP client, config, git integration",
		path: "packages/infra/core/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-infra-filesystem-Cargo-rust",
		label: "wrikka-filesystem",
		category: "Infra",
		description: "Filesystem utilities and operations with Clean Architecture",
		path: "packages/infra/filesystem/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-infra-networking-Cargo-rust",
		label: "wrikka-networking",
		category: "Infra",
		description: "Network communication utilities with Clean Architecture",
		path: "packages/infra/networking/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-infra-observability-Cargo-rust",
		label: "wrikka-observability",
		category: "Infra",
		description: "Monitoring and telemetry tools with Clean Architecture",
		path: "packages/infra/observability/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-infra-storage-Cargo-rust",
		label: "wrikka-storage",
		category: "Infra",
		description: "Storage abstractions with Clean Architecture",
		path: "packages/infra/storage/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-file-ops-Cargo-rust",
		label: "wrikka-file-ops",
		category: "Libraries",
		description:
			"wrikka-file-ops Rust workspace at packages/lib/file-ops/Cargo.toml",
		path: "packages/lib/file-ops/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-foundation-effect-cli-Cargo-rust",
		label: "wrikka-foundation-effect-cli",
		category: "Foundation",
		description: "CLI handler for effect system",
		path: "packages/lib/foundation/effect-cli/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-foundation-effect-core-Cargo-rust",
		label: "wrikka-foundation-effect-core",
		category: "Foundation",
		description: "Core effect system - pure types, cancellation, composition",
		path: "packages/lib/foundation/effect-core/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-foundation-effect-http-Cargo-rust",
		label: "wrikka-foundation-effect-http",
		category: "Foundation",
		description: "HTTP effect executor",
		path: "packages/lib/foundation/effect-http/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-foundation-error-Cargo-rust",
		label: "wrikka-foundation-error",
		category: "Foundation",
		description:
			"Error handling library with Clean Architecture and functional programming principles",
		path: "packages/lib/foundation/error/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-foundation-fp-Cargo-rust",
		label: "wrikka-foundation-fp",
		category: "Foundation",
		description: "Functional Programming library with Clean Architecture",
		path: "packages/lib/foundation/fp/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-foundation-utils-Cargo-rust",
		label: "wrikka-foundation-utils",
		category: "Foundation",
		description:
			"Utility library with Clean Architecture and functional programming principles",
		path: "packages/lib/foundation/utils/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-ratatui-ui-Cargo-rust",
		label: "ratatui-ui",
		category: "TUI Lib",
		description: "A shadcn/ui-style design system for ratatui TUI apps",
		path: "packages/lib/ratatui-ui/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tauri-plugin-wrikka-fs-Cargo-rust",
		label: "tauri-plugin-wrikka-fs",
		category: "Libraries",
		description:
			"High-performance file system plugin for Wrikka Desktop Explorer",
		path: "packages/lib/tauri-plugin-wrikka-fs/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tauri-plugin-wrikka-fs-examples-vanilla-package-npm",
		label: "app",
		category: "Libraries",
		description:
			"app npm workspace at packages/lib/tauri-plugin-wrikka-fs/examples/vanilla/package.json",
		path: "packages/lib/tauri-plugin-wrikka-fs/examples/vanilla/package.json",
		type: "npm",
	},
	{
		id: "packages-lib-tauri-plugin-wrikka-fs-examples-vanilla-src-tauri-Cargo-rust",
		label: "tauri-app",
		category: "Libraries",
		description: "A Tauri App",
		path: "packages/lib/tauri-plugin-wrikka-fs/examples/vanilla/src-tauri/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tools-cli-builder-Cargo-rust",
		label: "wrikka-cli-builder",
		category: "Tools",
		description: "A clean architecture CLI builder library",
		path: "packages/lib/tools/cli-builder/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tools-cli-builder-package-npm",
		label: "@wrikka/rust-cli-builder",
		category: "Tools",
		description: "CLI builder utilities with Clean Architecture",
		path: "packages/lib/tools/cli-builder/package.json",
		type: "npm",
	},
	{
		id: "packages-lib-tools-code-metrics-Cargo-rust",
		label: "wrikka-code-metrics",
		category: "Tools",
		description: "Code analysis metrics and quality measures",
		path: "packages/lib/tools/code-metrics/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tools-code-translation-Cargo-rust",
		label: "wrikka-code-translation",
		category: "Tools",
		description: "AI-powered code translation",
		path: "packages/lib/tools/code-translation/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tools-lsp-Cargo-rust",
		label: "wrikka-lsp",
		category: "Tools",
		description:
			"LSP integration - completion, diagnostics, and go-to-definition",
		path: "packages/lib/tools/lsp/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tools-parser-engine-Cargo-rust",
		label: "wrikka-parser-engine",
		category: "Tools",
		description:
			"Advanced parser utilities with multiple language support and Clean Architecture",
		path: "packages/lib/tools/parser-engine/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tools-parser-engine-package-npm",
		label: "@wrikka/rust-parser",
		category: "Tools",
		description:
			"Advanced parser utilities with multiple language support and Clean Architecture",
		path: "packages/lib/tools/parser-engine/package.json",
		type: "npm",
	},
	{
		id: "packages-lib-tools-perf-Cargo-rust",
		label: "wrikka-perf",
		category: "Tools",
		description: "Performance monitoring and benchmarking tools",
		path: "packages/lib/tools/perf/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tools-repo-mapping-Cargo-rust",
		label: "wrikka-repo-mapping",
		category: "Tools",
		description: "Repository map generation and analysis",
		path: "packages/lib/tools/repo-mapping/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tools-reporter-Cargo-rust",
		label: "wrikka-reporting",
		category: "Tools",
		description:
			"Generic reporting library with multiple formats, exporters, and Clean Architecture",
		path: "packages/lib/tools/reporter/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tools-rules-engine-Cargo-rust",
		label: "wrikka-rules-engine",
		category: "Tools",
		description:
			"Flexible and customizable rules engine for code analysis, linting, and rewriting - Clean Architecture",
		path: "packages/lib/tools/rules-engine/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tools-search-engine-Cargo-rust",
		label: "wrikka-search-engine",
		category: "Tools",
		description:
			"AI-friendly semantic search engine with AST parsing, following Clean Architecture principles",
		path: "packages/lib/tools/search-engine/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tools-template-engine-Cargo-rust",
		label: "wrikka-template-engine",
		category: "Tools",
		description: "General-purpose template engine for project generation",
		path: "packages/lib/tools/template-engine/Cargo.toml",
		type: "rust",
	},
	{
		id: "packages-lib-tools-template-engine-package-npm",
		label: "@wrikka/rust-template-engine",
		category: "Tools",
		description: "Template engine with Clean Architecture",
		path: "packages/lib/tools/template-engine/package.json",
		type: "npm",
	},
];

export const categories = Array.from(
	new Set(workspaces.map((w) => w.category)),
).sort();
